"""Add persistence tracking fields

Revision ID: 33aa8415b587
Revises: 5d05ca75996e
Create Date: 2026-07-24 20:18:11.517832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33aa8415b587'
down_revision: Union[str, None] = '5d05ca75996e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analysis_jobs', sa.Column('source_doc_path', sa.String(), nullable=True))
    op.add_column('requirements', sa.Column('raw_text', sa.String(), nullable=True))
    op.add_column('requirements', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requirements', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_cases', sa.Column('requirement_id', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_cases', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_cases', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_cases', sa.Column('llm_raw_response', sa.String(), nullable=True))
    op.add_column('test_cases', sa.Column('langsmith_run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'requirements', ['requirement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'langsmith_run_id')
    op.drop_column('test_cases', 'llm_raw_response')
    op.drop_column('test_cases', 'completed_at')
    op.drop_column('test_cases', 'updated_at')
    op.drop_column('test_cases', 'created_at')
    op.drop_column('test_cases', 'requirement_id')
    op.drop_column('requirements', 'updated_at')
    op.drop_column('requirements', 'created_at')
    op.drop_column('requirements', 'raw_text')
    op.drop_column('analysis_jobs', 'source_doc_path')
    op.drop_column('analysis_jobs', 'completed_at')
    # ### end Alembic commands ###
