"""Initial schema

Revision ID: 5d05ca75996e
Revises: 
Create Date: 2026-07-23 12:09:52.383122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d05ca75996e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('storage_backend', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_analysis_jobs_job_id'), 'analysis_jobs', ['job_id'], unique=False)
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('given_clause', sa.String(), nullable=True),
    sa.Column('when_clause', sa.String(), nullable=True),
    sa.Column('then_clause', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceptance_criteria_req_id'), 'acceptance_criteria', ['req_id'], unique=False)
    op.create_table('coverage_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('total_requirements', sa.Integer(), nullable=True),
    sa.Column('covered_requirements', sa.Integer(), nullable=True),
    sa.Column('coverage_percent', sa.Float(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('boundary_count', sa.Integer(), nullable=True),
    sa.Column('edge_count', sa.Integer(), nullable=True),
    sa.Column('priority_breakdown', sa.JSON(), nullable=True),
    sa.Column('missing_coverage', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_req_id'), 'requirements', ['req_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_req_id'), 'scenarios', ['req_id'], unique=False)
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('expected_result', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_req_id'), 'test_cases', ['req_id'], unique=False)
    op.create_index(op.f('ix_test_cases_scenario_id'), 'test_cases', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_id'), 'test_cases', ['test_id'], unique=False)
    op.create_table('traceability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('covered', sa.Boolean(), nullable=True),
    sa.Column('scenario_ids', sa.JSON(), nullable=True),
    sa.Column('test_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_req_id'), 'traceability', ['req_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traceability_req_id'), table_name='traceability')
    op.drop_table('traceability')
    op.drop_index(op.f('ix_test_cases_test_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_scenario_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_req_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_req_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_requirements_req_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('coverage_summaries')
    op.drop_index(op.f('ix_acceptance_criteria_req_id'), table_name='acceptance_criteria')
    op.drop_table('acceptance_criteria')
    op.drop_index(op.f('ix_analysis_jobs_job_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
